export const nepalProvinces = [
  {
    name: "Koshi Province",
    districts: [
      "Bhojpur",
      "Dhankuta",
      "Ilam",
      "Jhapa",
      "Khotang",
      "Morang",
      "Okhaldhunga",
      "Panchthar",
      "Sankhuwasabha",
      "Solukhumbu",
      "Sunsari",
      "Taplejung",
      "Terhathum",
      "Udayapur",
    ],
  },
  {
    name: "Madhesh Province",
    districts: [
      "Bara",
      "Dhanusha",
      "Mahottari",
      "Parsa",
      "Rautahat",
      "Saptari",
      "Sarlahi",
      "Siraha",
    ],
  },
  {
    name: "Bagmati Province",
    districts: [
      "Bhaktapur",
      "Chitwan",
      "Dhading",
      "Dolakha",
      "Kathmandu",
      "Kavrepalanchok",
      "Lalitpur",
      "Makwanpur",
      "Nuwakot",
      "Ramechhap",
      "Rasuwa",
      "Sindhuli",
      "Sindhupalchok",
    ],
  },
  {
    name: "Gandaki Province",
    districts: [
      "Baglung",
      "Gorkha",
      "Kaski",
      "Lamjung",
      "Manang",
      "Mustang",
      "Myagdi",
      "Nawalparasi",
      "Parbat",
      "Syangja",
      "Tanahu",
    ],
  },
  {
    name: "Lumbini Province",
    districts: [
      "Arghakhanchi",
      "Banke",
      "Bardiya",
      "Dang",
      "Gulmi",
      "Kapilvastu",
      "Nawalparasi",
      "Palpa",
      "Pyuthan",
      "Rolpa",
      "Rukum",
      "Rupandehi",
    ],
  },
  {
    name: "Karnali Province",
    districts: [
      "Dailekh",
      "Dolpa",
      "Humla",
      "Jajarkot",
      "Jumla",
      "Kalikot",
      "Mugu",
      "Rukum",
      "Salyan",
      "Surkhet",
    ],
  },
  {
    name: "Sudurpashchim Province",
    districts: [
      "Achham",
      "Baitadi",
      "Bajhang",
      "Bajura",
      "Dadeldhura",
      "Darchula",
      "Doti",
      "Kailali",
      "Kanchanpur",
    ],
  },
];

export const kathmanduValleyDistricts = [
  "Kathmandu",
  "Lalitpur",
  "Bhaktapur",
  "Kavrepalanchok",
  "Sindhupalchok",
];

export const deliveryZones = [
  {
    name: "Inside Kathmandu Valley",
    districts: kathmanduValleyDistricts,
    charge: 100,
    description: "Same day or next day delivery",
  },
  {
    name: "Outside Kathmandu Valley",
    districts: [
      "Chitwan",
      "Makwanpur",
      "Nuwakot",
      "Dhading",
      "Sindhuli",
      "Ramechhap",
      "Kaski",
      "Tanahu",
      "Gorkha",
      "Lamjung",
      "Syangja",
      "Nawalparasi",
      "Rupandehi",
      "Kapilvastu",
      "Dang",
      "Banke",
      "Bardiya",
      "Sunsari",
      "Morang",
      "Jhapa",
      "Ilam",
      "Dhankuta",
      "Sankhuwasabho",
      "Bhojpur",
      "Khotang",
      "Okhaldhunga",
      "Terhathum",
      "Udayapur",
      "Saptari",
      "Siraha",
      "Dhanusha",
      "Mahottari",
      "Sarlahi",
      "Rautahat",
      "Bara",
      "Parsa",
    ],
    charge: 150,
    description: "2-4 business days",
  },
  {
    name: "Remote Areas",
    districts: [
      "Dolpa",
      "Mugu",
      "Humla",
      "Jumla",
      "Kalikot",
      "Dailekh",
      "Jajarkot",
      "Rukum",
      "Rolpa",
      "Pyuthan",
      "Salyan",
      "Surkhet",
      "Bajura",
      "Bajhang",
      "Achham",
      "Doti",
      "Kailali",
      "Kanchanpur",
      "Dadeldhura",
      "Baitadi",
      "Darchula",
      "Taplejung",
      "Panchthar",
      "Solukhumbu",
      "Rasuwa",
      "Mustang",
      "Manang",
      "Myagdi",
      "Baglung",
      "Parbat",
      "Gulmi",
      "Palpa",
      "Arghakhanchi",
      "Nawalparasi",
    ],
    charge: 250,
    description: "5-7 business days",
  },
];
